<dl>
                                    <dt>
                                    <a href="[field:arcurl/]"  target="_blank" title="[field:title/]"> 
                                        <img src="[field:litpic/]" alt="[field:keywords/]" width="250" height="165"/> 
                                    </a>
                                    </dt>
                                    <dd>
                                        <h3><span class="dj">原创</span><a href="[field:arcurl/]"  target="_blank" title="[field:title/]">[field:title/]</a></h3>
                                        <p>[field:description/]</p>
                                        <p>[field:writer/]  /  [field:source/]  / [field:pubdate function="MyDate('Y-m-d H:i',@me)"/]</p>
                                    </dd>
                                </dl>
                            </div>