<div class="hljxddc-box m[field:global name=autoindex runphp='yes']@me=@me;[/field:global]">
                                    <div class="hljxddc-box-pic"><a href="[field:arcurl/]" target="_blank"><img src="[field:litpic/]" alt="[field:keywords/]" width='250' height='165'/></a></div>
                                    <div class="hljxddc-box-txt"><a href="[field:arcurl/]" target="_blank">[field:title/]</a></div>
                                </div>