<div class="hlbqy-box">

                                    <li>
                                        <dl>
                                            <dt><a href="[field:arcurl/]"  target="_blank" title="[field:title/]">[field:title/</a> </dt>
                                            <dd> [field:pubdate function="MyDate('Y-m-d H:i',@me)"/]</dd>
                                        </dl>                
                                    </li>

                                </div>