<li class="rtmj-box">
                                        <dl>
                                            <dt><a href="[field:arcurl/]"  target="_blank" title="[field:title/]"> <img src="[field:litpic/]" alt="[field:keywords/]" width="250" height="165"/> </a></dt>
                                            <dd>
                                                <h3><a href="[field:arcurl/]"  target="_blank" title="[field:title/]">[field:title/]</a></h3>
                                                <p>[field:description/]</p>
                                                <p>[field:writer/]  /  [field:source/]  / {dede:field.pubdate function="MyDate('Y-m-d H:i',@me)"/}</p>
                                            </dd>
                                    </li>